apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000       # This is the port for the Service
      targetPort: 80   # <--- THIS MUST BE 80 (because Nginx uses 80)
      nodePort: 30000